apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "client-manager.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: "{{ .Values.config.server.port }}"

    database:
      dsn: "{{ .Values.config.database.dsn }}"

    log:
      level: "{{ .Values.config.log.level }}"
      format: "{{ .Values.config.log.format }}"
      output: "{{ .Values.config.log.output }}"