apiVersion: v2
name: client-manager
description: A Helm chart for client-manager application
type: application
version: 0.1.0
appVersion: v0.2.1
keywords:
  - client-manager
  - api
  - service
home: https://github.com/zgsm/client-manager
sources:
  - https://github.com/zgsm/client-manager
maintainers:
  - name: zgsm
    email: zgsm@sangfor.com.cn
  - name: zbc
    email: zbc@sangfor.com.cn